<?php

namespace AppBundle\Repository;

/**
 * BultoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BultoRepository extends \Doctrine\ORM\EntityRepository
{
}
