<?php

namespace AppBundle\Repository;

/**
 * CuentasitemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentasitemRepository extends \Doctrine\ORM\EntityRepository
{
}
