<?php

namespace AppBundle\Repository;

/**
 * OrigentanspalmacenajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrigentanspalmacenajeRepository extends \Doctrine\ORM\EntityRepository
{
}
