version: "3"

services:
  nginx                   :
    image                 : nginx
    ports                 :
      - "8080:80"
    networks              :
      - app_network
    volumes               :
      - ./:/code
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      
  symfony                 :
    build                 : 
      context             : ./docker
      dockerfile          : Dockerfile
    networks              :
      - app_network
    volumes               :
      - ./:/code

  mariadb                 :
    container_name        : mariadb
    image                 : mariadb
    restart               : always
    environment           : 
      MYSQL_ROOT_PASSWORD : 12345
      MYSQL_DATABASE      : ejercicio_3
    volumes               :
      - ./databases:/var/lib/mysql
      - ./tableXML.sql:/docker-entrypoint-initdb.d/init.sql
    networks              :
      - app_network
    ports                 :
      - "3306:3306"

networks                  :
  app_network             :
    driver                : bridge