version: "3"

services:
  nginx                   :
    image                 : nginx
    ports                 :
      - "9999:80"
    networks              :
      - app_network
    volumes               :
      - ./:/code
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on            :
      - symfony
      
  symfony                 :
    build                 : 
      context             : .
      dockerfile          : Dockerfile
    links                 :
      - mariadb:mysql
    ports                 :
      - "9000:9000"
    networks              :
      - app_network
    volumes               :
      - ./:/code
    depends_on            :
      - mariadb

  mariadb                 :
    container_name        : mariadb
    image                 : mariadb
    restart               : always
    environment           : 
      MYSQL_ROOT_PASSWORD : 12345
      MYSQL_DATABASE      : ejercicio_3
    volumes               :
      - mariadb_data:/var/lib/mysql
    networks              :
      - app_network
    ports                 :
      - "127.0.0.1:9001:3306"

networks                  :
  app_network             :
    driver                : bridge

volumes                   :
  mariadb_data            :