version: "3"

services:
  nginx                   :
    image                 : nginx
    ports                 :
      - "8080:80"
    networks              :
      - app_network
    volumes               :
      - ./:/code
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on            :
      - symfony
      
  symfony                 :
    build                 : 
      context             : ./docker
      dockerfile          : Dockerfile
    links                 :
      - mariadb:mysql
    ports                 :
      - "9000:9000"
    networks              :
      - app_network
    volumes               :
      - ./:/code
    depends_on            :
      - mariadb

  mariadb                 :
    container_name        : mariadb
    image                 : mariadb
    restart               : always
    environment           : 
      MYSQL_ROOT_PASSWORD : 12345
      MYSQL_DATABASE      : ejercicio_3
    volumes               :
      - mariadb_data:/var/lib/mysql
      # - ./tableXML.sql:/docker-entrypoint-initdb.d/init.sql
    networks              :
      - app_network
    ports                 :
      - "127.0.0.1:3306:3306"

networks                  :
  app_network             :
    # driver                : bridge

volumes                   :
  mariadb_data            :