<?php

namespace AppBundle\Repository;

/**
 * AntecedentesfinancierosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntecedentesfinancierosRepository extends \Doctrine\ORM\EntityRepository
{
}
