<?php

namespace AppBundle\Repository;

/**
 * BultosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BultosRepository extends \Doctrine\ORM\EntityRepository
{
}
