<?php

namespace AppBundle\Repository;

/**
 * CabezaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CabezaRepository extends \Doctrine\ORM\EntityRepository
{
}
