<?php

namespace AppBundle\Repository;

/**
 * CuentasgiroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentasgiroRepository extends \Doctrine\ORM\EntityRepository
{
}
