<?php

namespace AppBundle\Repository;

/**
 * CuentasyvaloresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentasyvaloresRepository extends \Doctrine\ORM\EntityRepository
{
}
