<?php

namespace AppBundle\Repository;

/**
 * IdentificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
