<?php

namespace AppBundle\Repository;

/**
 * ObservacionesitemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservacionesitemRepository extends \Doctrine\ORM\EntityRepository
{
}
