<?php

namespace AppBundle\Repository;

/**
 * TipoEnvioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEnvioRepository extends \Doctrine\ORM\EntityRepository
{
}
