<?php

namespace AppBundle\Repository;

/**
 * TotalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TotalesRepository extends \Doctrine\ORM\EntityRepository
{
}
