<?php

namespace AppBundle\Repository;

/**
 * VistosbuenosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VistosbuenosRepository extends \Doctrine\ORM\EntityRepository
{
}
